calendarwww/src/Controllers/DayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;

using libcalendarman;


namespace calendarwww.Controllers
{
    public class DayController : Controller
    {
        //
        // GET: /Day/

        public ActionResult Index()
        {
            DateTime now = DateTime.Now;

            GregorianDate gd = new GregorianDate(now.Year, now.Month, now.Day);

            CalendarInfo ci = new CalendarInfo( (int) gd);


            return View("Day", ci );
        }


        public ActionResult Detail(int fd)
        {
            return View("Day", new CalendarInfo(fd));            
        }

    }
}

calendarwww/src/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;

using libcalendarman;


namespace calendarwww.Controllers
{
    public class EventController : Controller
    {
        static List<EventType> AllEventTypes;


        static EventController()
        {
            AllEventTypes = new List<EventType>();
            AllEventTypes.AddRange(GregorianDate.ChristianEventTypes);
            AllEventTypes.AddRange(GregorianDate.USEventTypes);
            AllEventTypes.AddRange(JulianDate.OrthodoxEventTypes);
        }


        private static List<Event> GetEvents(int gyear)
        {
            List<Event> l = new List<Event>();
            foreach (EventType et in AllEventTypes)
            {
                et.AddEvent(l, gyear);
            }
            return l;
        }


        public static List<Event> GetEvents(SettingsInfo si, int gregorianYear)
        {
            List<Event> events = new List<Event>();

            if (si.HebrewHolidays)
            {
                //events.AddRange(HebrewDate.GetHebrewEvents(gregorianYear));
            }

            if (si.ChristianHolidays)
            {
                events.AddRange(GregorianDate.GetChristianEvents(gregorianYear));
            }

            if (si.USHolidays)
            {
                events.AddRange(GregorianDate.GetUSEvents(gregorianYear));
            }

            return events;
        }


        public ActionResult Index()
        {
            return View();
        }


        //
        // GET: /Event/
        public ActionResult Day(int fd)
        {
            int gyear = GregorianDate.GetYearFromFixed(fd);

            
            CalendarInfo ci = new CalendarInfo(fd, GetEvents(gyear).Where( a => a.FixedDate == fd));
            
            return View(ci);
        }


        public ActionResult List(string evt, int fd)
        {
            int i = 0;

            return View();
        }

    }
}

calendarwww/src/Controllers/GregorianController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;

using libcalendarman;


namespace calendarwww.Controllers
{

    public class GregorianController : Controller
    {
        //
        // GET: /Gregorian/

        public ActionResult Index()
        {
            DateTime now = DateTime.Now;
            GregorianDate gd = new GregorianDate(now.Year, now.Month, now.Day);
            return RedirectToAction("Month", new { fd = gd.ToFixed() } );
        }


        public ActionResult Month(int fd)
        {
            int gregorianYear = GregorianDate.GetYearFromFixed(fd);

            List<Event> events = new List<Event>();

            SettingsInfo si = new SettingsInfo(Request.Cookies);
            // TODO Add hebrew events
            //if (si.HebrewHolidays)
            //{
            //    events.AddRange(HebrewDate.GetHebrewEvents(gregorianYear));
            //}

            if (si.ChristianHolidays)
            {
                events.AddRange(GregorianDate.GetChristianEvents(gregorianYear));
            }

            if (si.USHolidays)
            {
                events.AddRange(GregorianDate.GetUSEvents(gregorianYear));
            }

            CalendarInfo ci = new CalendarInfo(fd, events);
            ci.Settings = si;
            

            return View("Month", ci);
        }


        public ActionResult Year(int fd)
        {
            CalendarInfo ci = new CalendarInfo(fd);

            return View("Year", ci);
        }

    }
}

calendarwww/src/Controllers/JulianController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;

using libcalendarman;


namespace calendarwww.Controllers
{

    public class JulianController : Controller
    {
        //
        // GET: /Gregorian/

        public ActionResult Index()
        {
			DateTime now = DateTime.Now;

            List<Event> events = new List<Event>();

            

            return View("Month", new CalendarInfo(new GregorianDate(now.Year, now.Month, now.Day), events));
        }


        public ActionResult Month(int fd)
        {
            List<Event> events = new List<Event>();

            return View("Month", new CalendarInfo(new JulianDate(fd), events));
        }

    }
}

calendarwww/src/Views/Day/Day.cshtml
@model calendarwww.Controllers.CalendarInfo
@using libcalendarman;

@{
    ViewBag.Title = "Day";
    Layout = "~/Views/Shared/SiteLayout.cshtml";

    GregorianDate gd = new GregorianDate(Model.Date);
    ISODate isod = new ISODate(Model.Date);
    JulianDate jd = new JulianDate(Model.Date);
    RomanDate romand = new RomanDate(Model.Date);
    HebrewDate hd = new HebrewDate(Model.Date);
    IslamicDate id = new IslamicDate(Model.Date);
    EgyptianDate egd = new EgyptianDate(Model.Date);
    CopticDate cd = new CopticDate(Model.Date);
    ArmenianDate ad = new ArmenianDate(Model.Date);
    EthiopicDate ethd = new EthiopicDate(Model.Date);
}


<h2>Day @Model.Date.ToString("N0")</h2>
    <table>
        <tr>
            <th>Calendar</th>
            <th>Date</th>
            <th>Navigation</th>
        </tr>
        <tr>
            <td>Gregorian</td>
            <td>@Html.ActionLink(gd.ToString(), "Detail", "Gregorian", new { fd = Model.Date }, null)</td>
            <td>
                @Html.ActionLink("Previous Month", "Detail", new { fd = gd.PreviousMonth }, null)
                @Html.ActionLink("Next Month", "Detail", new { fd = gd.NextMonth }, null)
            </td>
        </tr>
        <tr>
            <td>ISO</td>
            <td>@isod.ToString()</td>
        </tr>
        <tr>
            <td>Julian</td>
            <td>@Html.ActionLink(jd.ToString(), "Detail", "Julian", new { fd = Model.Date }, null)</td>
            <td>
                @Html.ActionLink("Previous Month", "Detail", new { fd = jd.PreviousMonth }, null) 
                @Html.ActionLink("Next Month", "Detail", new { fd = jd.NextMonth }, null)
            </td>
        </tr>
        <tr>
            <td>JulianDate</td>
            <td>@jd.JulianDay.ToString("N1")</td>
        </tr>
        <tr>
            <td>Modified Julian Date</td>
            <td>@jd.ModifiedJulianDay.ToString("N0")</td>
        </tr>
        <tr>
            <td>Roman</td>
            <td>@romand.ToString()</td>
        </tr>
        <tr>
            <td>Hebrew</td>
            <td>@hd.ToString()</td>
        
        </tr>
        <tr>
            <td>Islamic</td>
            <td>@id.ToString()</td>
        </tr>
        <tr>
            <td>Egyptian</td>
            <td>@egd.ToString()</td>
        </tr>
        <tr>
            <td>Coptic</td>
            <td>@cd.ToString()</td>
        </tr>
        <tr>
            <td>Armenisan</td>
            <td>@ad.ToString()</td>
        </tr>
        <tr>
            <td>Ethiopic</td>
            <td>@ethd.ToString()</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td>
                @Html.ActionLink("Last Week", "Detail", new { fd = Model.Date - 7 }, null) 
                @Html.ActionLink("Yesterday", "Detail", new { fd = Model.Date - 1 }, null)  
                @Html.ActionLink("Tomorrow", "Detail", new { fd = Model.Date + 1 }, null)  
                @Html.ActionLink("Next Week", "Detail", new { fd = Model.Date + 7 }, null)  
            </td>
        </tr>

        <tr>
            <td>Events</td>
            <td>
            @foreach (Event evt in Model.Events)
            {
                <p>@Html.ActionLink(evt.Type.Name, evt.Type.Name, "Event", new {fd = evt.FixedDate } )</p>
            }
            </td>
        </tr>
    </table>



@section LeftContent
{
    @{ Html.RenderPartial("LeftContent", Model); }
}
